name: Build & Deploy Pages

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Turn on Pages for this repo
      - name: Enable Pages
        uses: actions/configure-pages@v4
        with:
          enablement: github_enabled   # this registers your site

      # 2) Build your site with Jekyll (or just skip to upload if you removed custom build)
      - name: Build
        run: bundle exec jekyll build --destination _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      # 3) Deploy
      - name: Deploy
        uses: actions/deploy-pages@v4
